# Generated by Django 3.2.3 on 2021-05-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_of_day', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM'), ('EVE', 'EVE')], max_length=3)),
                ('capacity', models.PositiveIntegerField()),
                ('unavailable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('date', 'time_of_day'),
            },
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('date', 'time_of_day'), name='unique_slot'),
        ),
    ]
